In [3]:
import pandas as pd

measurements = pd.read_csv("resources/b2w.csv")

measurements.head()

   original_index  ... kfold_rating
0           11955  ...            1
1           35478  ...            1
2          122760  ...            1
3           17114  ...            1
4           19112  ...            1

[5 rows x 8 columns]

In [4]:
clean_measurements = measurements.drop(axis=1, labels=["original_index", "review_text_processed", "review_text_tokenized", "kfold_polarity", "kfold_rating", "rating"], )

clean_measurements.head()

                                         review_text  polarity
0  Bem macio e felpudo...recomendo.  Preço imbatí...       1.0
1  Produto excepcional!  recomendo!!! inovador e ...       1.0
2  recebi o produto antes do prazo mas veio com d...       0.0
3  Bom custo beneficio. Adequado para pessoas que...       1.0
4  Além de higiênico tem o tamanho ideal. Só falt...       NaN

In [5]:
clean_measurements.dropna(inplace=True, axis=0)
clean_measurements.head()

                                         review_text  polarity
0  Bem macio e felpudo...recomendo.  Preço imbatí...       1.0
1  Produto excepcional!  recomendo!!! inovador e ...       1.0
2  recebi o produto antes do prazo mas veio com d...       0.0
3  Bom custo beneficio. Adequado para pessoas que...       1.0
5  ótmo produto atendeu as expectativas, a entreg...       1.0

In [6]:
clean_measurements.polarity.value_counts()

polarity
1.0    80300
0.0    35758
Name: count, dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

train, test, train_class, test_class = train_test_split(
    measurements.review_text, 
    measurements.polarity,
    stratify=measurements.polarity,
    random_state=71)

ValueError: Input y contains NaN.

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train, train_class)
accuracy = lr.score(test, test_class)
accuracy

NameError: name 'train' is not defined